# -*- coding: utf-8 -*-
"""dictionary_validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WUPJ-xEWHk7f98TppSHOJSn873kzkSAH
"""

##############################################################################
# DICTIONARY RELIABILITY & VALIDITY — EMBEDDING-BASED COSINE SIMILARITY
# Model  : all-mpnet-base-v2 (Reimers & Gurevych, 2019)
# Method : Replicates and extends Nicolas et al. (2020)
# Runs reliability on BOTH seed and expanded dictionaries
##############################################################################

# CONFIGURATION

DRIVE_PATH     = "/content/gdrive/My Drive/Colab Notebooks/main_dissertation_analysis/dictionaries"
MODEL_NAME     = "all-mpnet-base-v2"
OUTPUT_PATH    = DRIVE_PATH
SCRIPT_VERSION = "2.0"

# Expanded dictionary file names
EXPANDED_FILES = {
    # Target
    "AIM" : "AIM_dictionary.csv",
    "CIM" : "CIM_dictionary.csv",
    "IM"  : "IM_dictionary.csv",
    # Convergent
    "Pietraszkiewicz_Agency"   : "Pietraszkiewicz_agency.csv",
    "Pietraszkiewicz_Communion": "Pietraszkiewicz_communion.csv",
    "LIWC_Achievement"         : "LIWC_achieve.csv",
    "LIWC_Affiliation"         : "LIWC_affiliation.csv",
    # Discriminant
    "LIWC_Health"              : "LIWC_health.csv",
    "LIWC_Tech"                : "LIWC_tech.csv",
}

# Seed dictionary file names (target dicts only)
SEED_FILES = {
    "AIM_seed" : "AIM_seed_dictionary.csv",
    "CIM_seed" : "CIM_seed_dictionary.csv",
    "IM_seed"  : "IM_seed_dictionary.csv",
}

# INSTALL & IMPORTS

import subprocess, sys

def install(pkg):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])

install("sentence-transformers")

import os
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
from scipy import stats
from sentence_transformers import SentenceTransformer

# MOUNT GOOGLE DRIVE

from google.colab import drive
drive.mount("/content/gdrive", force_remount=False)

# DEFINE FUNCTIONS

def strip_wildcards(word: str) -> str:
    """Remove LIWC-style wildcards (* and .) from word stems."""
    return re.sub(r"[\*\.\+]$", "", str(word).strip())

def load_dictionary(filepath: str) -> list:
    """
    Load a single-column CSV dictionary.
    Recovers the header row as a word (LIWC CSVs use first word as header).
    Strips wildcards, lowercases, deduplicates. Returns a sorted list.
    """
    df = pd.read_csv(filepath, header=0, dtype=str)
    header_word = df.columns[0]
    words = [header_word] + df.iloc[:, 0].dropna().tolist()
    cleaned = list({strip_wildcards(w).lower().strip()
                    for w in words if w.strip() != ""})
    return sorted(cleaned)

def cosine_similarity(a: np.ndarray, b: np.ndarray) -> float:
    """Cosine similarity between two average vectors."""
    denom = np.linalg.norm(a) * np.linalg.norm(b)
    if denom == 0:
        return 0.0
    return float(np.dot(a, b) / denom)

def pairwise_cosine_matrix(vectors: np.ndarray) -> np.ndarray:
    """Full pairwise cosine similarity matrix for a set of vectors."""
    norms = np.linalg.norm(vectors, axis=1, keepdims=True)
    norms = np.where(norms == 0, 1e-10, norms)
    normed = vectors / norms
    return normed @ normed.T

def cronbach_alpha_cosine(sim_matrix: np.ndarray) -> float:
    """
    Cronbach's alpha analog using cosine similarities as inter-item correlations.
    Follows Nicolas et al. (2020) / Chakrabartty (2018).
    Note: inflated for very large n; interpret with caution.
    """
    n = sim_matrix.shape[0]
    if n < 2:
        return np.nan
    upper = sim_matrix[np.triu_indices(n, k=1)]
    mean_r = np.mean(upper)
    alpha = (n * mean_r) / (1 + (n - 1) * mean_r)
    return float(alpha)

def reliability_stats(name: str, words: list, word2vec: dict) -> dict:
    """Compute reliability statistics for a single dictionary."""
    vecs = np.array([word2vec[w] for w in words if w in word2vec])
    n = len(vecs)
    if n < 2:
        return None
    sim_matrix = pairwise_cosine_matrix(vecs)
    upper = sim_matrix[np.triu_indices(n, k=1)]
    within_mean = float(np.mean(upper))
    within_sd   = float(np.std(upper))
    alpha       = cronbach_alpha_cosine(sim_matrix)
    return {
        "Dictionary"      : name,
        "N_words"         : n,
        "Mean_within_sim" : round(within_mean, 4),
        "SD_within_sim"   : round(within_sd, 4),
        "Cronbach_alpha"  : round(alpha, 4),
    }

def ttest_within_between(target_names: list,
                         all_dict_names: list,
                         dictionaries: dict,
                         dict_vectors: dict,
                         word2vec: dict,
                         label: str) -> dict:
    """
    t-test: within-dictionary similarity > between-dictionary similarity.
    Replicates Nicolas et al. (2020) approach.
    """
    all_within = []
    for name in target_names:
        words = dictionaries[name]
        vecs  = np.array([word2vec[w] for w in words if w in word2vec])
        if len(vecs) < 2:
            continue
        sim_matrix = pairwise_cosine_matrix(vecs)
        n = len(vecs)
        upper = sim_matrix[np.triu_indices(n, k=1)]
        all_within.extend(upper.tolist())

    all_between = []
    names = list(all_dict_names)
    for i, n1 in enumerate(names):
        for j, n2 in enumerate(names):
            if j <= i:
                continue
            if n1 in dict_vectors and n2 in dict_vectors:
                sim = cosine_similarity(dict_vectors[n1], dict_vectors[n2])
                all_between.append(sim)

    t_stat, p_val = stats.ttest_ind(all_within, all_between,
                                    alternative="greater")
    pooled_sd = np.std(all_within + all_between)
    d = (np.mean(all_within) - np.mean(all_between)) / pooled_sd if pooled_sd > 0 else np.nan

    print(f"\n  t-test within > between [{label}]:")
    print(f"    M_within  = {np.mean(all_within):.4f}  (n = {len(all_within):,})")
    print(f"    M_between = {np.mean(all_between):.4f}  (n = {len(all_between):,})")
    print(f"    t = {t_stat:.4f}, p = {p_val:.4f}, d = {d:.4f}")

    return {
        "label"     : label,
        "M_within"  : round(np.mean(all_within), 4),
        "M_between" : round(np.mean(all_between), 4),
        "t"         : round(t_stat, 4),
        "p"         : round(p_val, 4),
        "d"         : round(d, 4),
    }

# LOAD DICTIONARIES

print("=" * 65)
print(f"DICTIONARY RELIABILITY & VALIDITY  |  v{SCRIPT_VERSION}")
print("=" * 65)
print(f"\nModel : {MODEL_NAME}")
print(f"Path  : {DRIVE_PATH}\n")

# Load expanded
expanded_dicts = {}
for name, fname in EXPANDED_FILES.items():
    fpath = os.path.join(DRIVE_PATH, fname)
    words = load_dictionary(fpath)
    expanded_dicts[name] = words
    print(f"  Loaded (expanded) {name:<32} {len(words):>6} words")

print()

# Load seed
seed_dicts = {}
for name, fname in SEED_FILES.items():
    fpath = os.path.join(DRIVE_PATH, fname)
    words = load_dictionary(fpath)
    seed_dicts[name] = words
    print(f"  Loaded (seed)     {name:<32} {len(words):>6} words")

# EMBED ALL UNIQUE WORDS IN A SINGLE PASS

print(f"\nEncoding with {MODEL_NAME}...")

all_words = sorted({
    w
    for d in [expanded_dicts, seed_dicts]
    for words in d.values()
    for w in words
})
print(f"  Unique words to encode: {len(all_words):,}")

model = SentenceTransformer(MODEL_NAME)
all_embeddings = model.encode(
    all_words,
    batch_size=256,
    show_progress_bar=True,
    convert_to_numpy=True
)

word2vec = {word: all_embeddings[i] for i, word in enumerate(all_words)}
print("  Encoding complete.\n")

# COMPUTE AVERAGE DICTIONARY VECTORS

def compute_dict_vectors(dictionaries: dict, word2vec: dict) -> dict:
    vectors = {}
    for name, words in dictionaries.items():
        vecs = np.array([word2vec[w] for w in words if w in word2vec])
        if len(vecs) == 0:
            print(f"  WARNING: No embeddings found for {name}")
            continue
        vectors[name] = vecs.mean(axis=0)
    return vectors

expanded_vectors = compute_dict_vectors(expanded_dicts, word2vec)
seed_vectors     = compute_dict_vectors(seed_dicts, word2vec)

# INTERNAL RELIABILITY - TARGET DICTIONARIES ONLY

print("=" * 65)
print("INTERNAL RELIABILITY")
print("=" * 65)

target_expanded = ["AIM", "CIM", "IM"]
target_seed     = ["AIM_seed", "CIM_seed", "IM_seed"]

# --- Seed dictionaries ---
print("\n  [ SEED DICTIONARIES ]\n")
seed_reliability = []
for name in target_seed:
    stats_dict = reliability_stats(name, seed_dicts[name], word2vec)
    if stats_dict:
        seed_reliability.append(stats_dict)
        print(f"  {name}")
        print(f"    Words embedded  : {stats_dict['N_words']}")
        print(f"    Mean within-sim : {stats_dict['Mean_within_sim']:.4f}"
              f"  (SD = {stats_dict['SD_within_sim']:.4f})")
        print(f"    Cronbach alpha  : {stats_dict['Cronbach_alpha']:.4f}")

# Between-sim for seed dicts
print("\n  Between-dictionary similarities (seed):")
seed_between = []
for i, n1 in enumerate(target_seed):
    for j, n2 in enumerate(target_seed):
        if j <= i:
            continue
        sim = cosine_similarity(seed_vectors[n1], seed_vectors[n2])
        seed_between.append(sim)
        print(f"    {n1} vs {n2}: {sim:.4f}")
print(f"  Mean between-sim (seed): {np.mean(seed_between):.4f}")

ttest_seed = ttest_within_between(
    target_seed, list(seed_dicts.keys()),
    seed_dicts, seed_vectors, word2vec,
    label="seed"
)

# --- Expanded dictionaries ---
print("\n  [ EXPANDED DICTIONARIES ]\n")
expanded_reliability = []
for name in target_expanded:
    stats_dict = reliability_stats(name, expanded_dicts[name], word2vec)
    if stats_dict:
        expanded_reliability.append(stats_dict)
        print(f"  {name}")
        print(f"    Words embedded  : {stats_dict['N_words']:,}")
        print(f"    Mean within-sim : {stats_dict['Mean_within_sim']:.4f}"
              f"  (SD = {stats_dict['SD_within_sim']:.4f})")
        print(f"    Cronbach alpha  : {stats_dict['Cronbach_alpha']:.4f}"
              f"  [note: inflated at n > 1,000]")

# Between-sim for expanded dicts
print("\n  Between-dictionary similarities (expanded):")
exp_between = []
for i, n1 in enumerate(target_expanded):
    for j, n2 in enumerate(target_expanded):
        if j <= i:
            continue
        sim = cosine_similarity(expanded_vectors[n1], expanded_vectors[n2])
        exp_between.append(sim)
        print(f"    {n1} vs {n2}: {sim:.4f}")
print(f"  Mean between-sim (expanded): {np.mean(exp_between):.4f}")

ttest_expanded = ttest_within_between(
    target_expanded, list(expanded_dicts.keys()),
    expanded_dicts, expanded_vectors, word2vec,
    label="expanded"
)

# Save reliability results
rel_seed_df     = pd.DataFrame(seed_reliability)
rel_expanded_df = pd.DataFrame(expanded_reliability)

rel_seed_path     = os.path.join(OUTPUT_PATH, "reliability_seed.csv")
rel_expanded_path = os.path.join(OUTPUT_PATH, "reliability_expanded.csv")
rel_seed_df.to_csv(rel_seed_path, index=False)
rel_expanded_df.to_csv(rel_expanded_path, index=False)
print(f"\n  Saved: {rel_seed_path}")
print(f"  Saved: {rel_expanded_path}")

# VALIDITY — FULL COSINE SIMILARITY MATRIX

print("\n" + "=" * 65)
print("VALIDITY — COSINE SIMILARITY MATRIX (EXPANDED DICTIONARIES)")
print("=" * 65)

dict_names = list(expanded_vectors.keys())
n_dicts    = len(dict_names)
sim_matrix_full = np.zeros((n_dicts, n_dicts))

for i, n1 in enumerate(dict_names):
    for j, n2 in enumerate(dict_names):
        sim_matrix_full[i, j] = cosine_similarity(
            expanded_vectors[n1], expanded_vectors[n2]
        )

sim_df = pd.DataFrame(sim_matrix_full, index=dict_names, columns=dict_names)

print("\n  Similarity matrix (rounded to 3 dp):")
print(sim_df.round(3).to_string())

val_path = os.path.join(OUTPUT_PATH, "validity_similarity_matrix.csv")
sim_df.round(4).to_csv(val_path)
print(f"\n  Saved: {val_path}")

# HEATMAP VISUALIZATION — TWO SEPARATE HEATMAPS

print("\nGenerating heatmaps...")

def plot_heatmap(sim_df, title, save_path, n_target, n_convergent, n_discriminant):
    """Plot and save a labeled cosine similarity heatmap."""
    dict_names    = list(sim_df.index)
    n_dicts       = len(dict_names)
    display_labels = [n.replace("_", " ") for n in dict_names]

    fig, ax = plt.subplots(figsize=(13, 10))

    sns.heatmap(
        sim_df,
        annot=True,
        fmt=".3f",
        cmap="RdYlGn",
        vmin=0,
        vmax=1,
        linewidths=0.5,
        linecolor="white",
        square=True,
        xticklabels=display_labels,
        yticklabels=display_labels,
        ax=ax,
        cbar_kws={"label": "Cosine Similarity", "shrink": 0.8}
    )

    ax.set_title(title, fontsize=14, fontweight="bold", pad=15)
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha="right", fontsize=10)
    ax.set_yticklabels(ax.get_yticklabels(), rotation=0, fontsize=10)

    # Dividing lines between groups
    boundary_1 = n_target
    boundary_2 = n_target + n_convergent
    for line_pos in [boundary_1, boundary_2]:
        ax.axhline(y=line_pos, color="black", linewidth=2)
        ax.axvline(x=line_pos, color="black", linewidth=2)

    # Group labels on right side
    group_labels = [
        (n_target / 2,                              "Target"),
        (n_target + n_convergent / 2,               "Convergent"),
        (n_target + n_convergent + n_discriminant / 2, "Discriminant"),
    ]
    for y_pos, label in group_labels:
        ax.text(
            n_dicts + 0.3, y_pos, label,
            va="center", ha="left", fontsize=9,
            fontstyle="italic", color="dimgray"
        )

    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.show()
    print(f"  Saved: {save_path}")


# --- Heatmap 1: Expanded dictionaries ---
plot_heatmap(
    sim_df   = sim_df,
    title    = f"Dictionary Cosine Similarity Matrix — Expanded\n({MODEL_NAME})",
    save_path = os.path.join(OUTPUT_PATH, "similarity_heatmap_expanded.png"),
    n_target      = 3,   # AIM, CIM, IM
    n_convergent  = 4,   # Pietraszkiewicz x2, LIWC Achievement, LIWC Affiliation
    n_discriminant = 2,  # LIWC Health, LIWC Tech
)

# --- Heatmap 2: Seed dictionaries ---
# Build seed similarity matrix including validation dictionaries
seed_and_val_names = list(seed_vectors.keys()) + [
    k for k in expanded_vectors.keys() if k not in target_expanded
]

n_seed_val = len(seed_and_val_names)
seed_sim_matrix = np.zeros((n_seed_val, n_seed_val))

for i, n1 in enumerate(seed_and_val_names):
    for j, n2 in enumerate(seed_and_val_names):
        v1 = seed_vectors.get(n1, expanded_vectors.get(n1))
        v2 = seed_vectors.get(n2, expanded_vectors.get(n2))
        if v1 is not None and v2 is not None:
            seed_sim_matrix[i, j] = cosine_similarity(v1, v2)

seed_sim_df = pd.DataFrame(
    seed_sim_matrix,
    index=seed_and_val_names,
    columns=seed_and_val_names
)

# Save seed validity matrix
seed_val_path = os.path.join(OUTPUT_PATH, "validity_similarity_matrix_seed.csv")
seed_sim_df.round(4).to_csv(seed_val_path)
print(f"  Saved: {seed_val_path}")

plot_heatmap(
    sim_df    = seed_sim_df,
    title     = f"Dictionary Cosine Similarity Matrix — Seed\n({MODEL_NAME})",
    save_path = os.path.join(OUTPUT_PATH, "similarity_heatmap_seed.png"),
    n_target      = 3,   # AIM_seed, CIM_seed, IM_seed
    n_convergent  = 4,   # Pietraszkiewicz x2, LIWC Achievement, LIWC Affiliation
    n_discriminant = 2,  # LIWC Health, LIWC Tech
)

print("\nHeatmap generation complete.")

# SUMMARY

print("\n" + "=" * 65)
print("COMPLETE — Output files:")
print(f"  {rel_seed_path}")
print(f"  {rel_expanded_path}")
print(f"  {val_path}")
print(f"  {heatmap_path}")
print("=" * 65)