# -*- coding: utf-8 -*-
"""gpt-4o.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JpZSFp_Hz75FYhS1YuT-q-6__v-_aCas
"""

# INSTALLS

!pip install -q openai

# CONFIGURATION

SCRIPT_VERSION = "1.0"

# All 24 combinations are run automatically.
# Each entry is (classification, dimension, text_col, prompt).
# - classification: which data file to load (agentic_AM.csv, communal_CM.csv, etc.)
# - dimension:      which BIMI_mean column is the target (AM or CM)
# - text_col:       which SJT text column to use as input
# - prompt:         which system prompt to apply (AM or CM)

RUNS = [
    # --- agentic / AM ---
    ("agentic", "AM", "SJTs_all", "AM"),
    ("agentic", "AM", "SJT_AM",   "AM"),
    ("agentic", "AM", "SJT_CM",   "AM"),
    ("agentic", "AM", "SJTs_all", "CM"),
    ("agentic", "AM", "SJT_AM",   "CM"),
    ("agentic", "AM", "SJT_CM",   "CM"),
    # --- agentic / CM ---
    ("agentic", "CM", "SJTs_all", "CM"),
    ("agentic", "CM", "SJT_AM",   "CM"),
    ("agentic", "CM", "SJT_CM",   "CM"),
    ("agentic", "CM", "SJTs_all", "AM"),
    ("agentic", "CM", "SJT_AM",   "AM"),
    ("agentic", "CM", "SJT_CM",   "AM"),
    # --- communal / CM ---
    ("communal", "CM", "SJTs_all", "CM"),
    ("communal", "CM", "SJT_AM",   "CM"),
    ("communal", "CM", "SJT_CM",   "CM"),
    ("communal", "CM", "SJTs_all", "AM"),
    ("communal", "CM", "SJT_AM",   "AM"),
    ("communal", "CM", "SJT_CM",   "AM"),
    # --- communal / AM ---
    ("communal", "AM", "SJTs_all", "AM"),
    ("communal", "AM", "SJT_AM",   "AM"),
    ("communal", "AM", "SJT_CM",   "AM"),
    ("communal", "AM", "SJTs_all", "CM"),
    ("communal", "AM", "SJT_AM",   "CM"),
    ("communal", "AM", "SJT_CM",   "CM"),
]

# GPT-4o model string — saves to output CSV for reproducibility records.
# OpenAI pins dated snapshots (e.g., gpt-4o-2024-11-20); using "gpt-4o"
# resolves to the current default snapshot at time of call.
# To pin a specific snapshot, replace with e.g. "gpt-4o-2024-11-20".
MODEL_ID = "gpt-4o"

# Rate limiting — requests per minute allowed.
# Tier 1 (default for new accounts): ~500 RPM.
# Reduce if you see frequent rate limit errors.
REQUESTS_PER_MINUTE = 400

# IMPORTS, DRIVE MOUNT, PATHS

import os
import re
import time
import numpy as np
import pandas as pd
from scipy.stats import pearsonr
from sklearn.metrics import mean_squared_error
from google.colab import drive
from openai import OpenAI

drive.mount("/content/gdrive", force_remount=True)

BASE_DIR   = "/content/gdrive/My Drive/Colab Notebooks/main_dissertation_analysis"
DATA_DIR   = f"{BASE_DIR}/data"
OUTPUT_DIR = f"{BASE_DIR}/outputs"
os.makedirs(f"{OUTPUT_DIR}/decoder_predictions", exist_ok=True)

# API CLIENT

try:
    from google.colab import userdata
    api_key = userdata.get("OPENAI_TOKEN")
    print("OpenAI API key loaded from Colab Secrets.")
except Exception:
    api_key = input("Enter your OpenAI API key: ")

client = OpenAI(api_key=api_key)

# Verify key and retrieve exact model snapshot being used
print(f"\nVerifying API connection...")
try:
    test = client.chat.completions.create(
        model=MODEL_ID,
        messages=[{"role": "user", "content": "Reply with the single digit 1."}],
        max_tokens=5,
    )
    model_snapshot = test.model   # e.g. "gpt-4o-2024-11-20"
    print(f"Connected successfully.")
    print(f"Model snapshot (for your records): {model_snapshot}")
except Exception as e:
    raise RuntimeError(f"API connection failed: {e}")

# SYSTEM PROMPTS

SYSTEM_PROMPTS = {

    "AM": """
You are an expert organizational psychologist specializing in workplace behavior
and impression management. You are evaluating written responses to situational
judgment test scenarios in a professional workplace context.

Your task is to rate each response on how strongly it reflects agentic impression
management — the degree to which the response involves strategic
self-presentation aimed at conveying competence, control, independence, and
goal-directed effectiveness. This includes emphasizing initiative, achievement,
decisiveness, and leadership in contexts where performance and status are salient.

Indicators of high AIM in a response include:
- Taking charge, leading, or directing action
- Solving problems efficiently and decisively
- Making confident, independent decisions
- Demonstrating competence or capability under pressure
- Focusing on outcomes, results, and performance

Use the following 1–7 scale:
1 = No agentic impression management evident.
2 = Very little agentic impression management evident.
3 = Slight agentic impression management evident.
4 = Moderate agentic impression management evident.
5 = Clear agentic impression management evident.
6 = Strong agentic impression management evident.
7 = Very strong agentic impression management evident.

Do not return any text or explanation. Do not repeat the prompt.
Return only a single integer between 1 and 7.
""".strip(),

    "CM": """
You are an expert organizational psychologist specializing in workplace behavior
and impression management. You are evaluating written responses to situational
judgment test scenarios in a professional workplace context.

Your task is to rate each response on how strongly it reflects communal impression
management — the degree to which the response involves strategic
self-presentation aimed at conveying warmth, care, cooperativeness, and
interpersonal consideration. This includes emphasizing support for others,
sensitivity to relationships, and a concern for group harmony in contexts where
social perception and likability are salient.

Indicators of high CIM in a response include:
- Expressing concern for others' feelings, needs, or wellbeing
- Offering help, support, or encouragement without being asked
- Deferring to others or seeking consensus rather than acting unilaterally
- Acknowledging team contributions or shared credit
- Prioritizing relationship preservation over task efficiency

Use the following 1–7 scale:
1 = No communal impression management evident.
2 = Very little communal impression management evident.
3 = Slight communal impression management evident.
4 = Moderate communal impression management evident.
5 = Clear communal impression management evident.
6 = Strong communal impression management evident.
7 = Very strong communal impression management evident.

Do not return any text or explanation. Do not repeat the prompt.
Return only a single integer between 1 and 7.
""".strip(),

}

USER_PROMPT_TEMPLATE = "Workplace scenario response:\n\"{sjt_response}\"\n\nRating:"

# RATING FUNCTION

# Minimum delay between requests to respect rate limit
REQUEST_DELAY = 60.0 / REQUESTS_PER_MINUTE

def get_bimi_rating(sjt_response: str, prompt: str,
                    max_retries: int = 5) -> int | None:
    """
    Sends a single SJT response to the GPT-4o API and returns an integer
    rating from 1–7. Implements exponential backoff for rate limit errors.
    Returns None if no valid integer can be parsed after all retries.
    """
    user_content = USER_PROMPT_TEMPLATE.format(sjt_response=sjt_response)

    for attempt in range(max_retries):
        try:
            response = client.chat.completions.create(
                model=MODEL_ID,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPTS[prompt]},
                    {"role": "user",   "content": user_content},
                ],
                max_tokens=5,
                temperature=0.0,    # greedy decoding — deterministic output
            )
            raw_output = response.choices[0].message.content.strip()

            # Extract first valid 1–7 integer
            match = re.search(r'\b([1-7])\b', raw_output)
            if match:
                time.sleep(REQUEST_DELAY)
                return int(match.group(1))

            print(f"  Warning: unexpected output '{raw_output}' "
                  f"for: {sjt_response[:60]}...")
            time.sleep(REQUEST_DELAY)
            return None

        except Exception as e:
            error_str = str(e).lower()
            if "rate_limit" in error_str or "429" in error_str:
                wait = (2 ** attempt) * 5   # 5s, 10s, 20s, 40s, 80s
                print(f"  Rate limit hit — waiting {wait}s before retry "
                      f"(attempt {attempt + 1}/{max_retries})...")
                time.sleep(wait)
            else:
                print(f"  API error: {e}")
                time.sleep(REQUEST_DELAY)
                return None

    print(f"  Max retries exceeded for: {sjt_response[:60]}...")
    return None

# COST ESTIMATION

# Approximate gpt-4o pricing (as of 2024): $2.50/M input tokens, $10/M output
INPUT_COST_PER_TOKEN  = 2.50 / 1_000_000
OUTPUT_COST_PER_TOKEN = 10.0 / 1_000_000

total_input_tokens  = 0
total_output_tokens = 0

def get_bimi_rating_tracked(sjt_response: str, prompt: str) -> int | None:
    """
    Wrapper around get_bimi_rating that also tracks token usage for cost
    estimation. Updates global token counters.
    """
    global total_input_tokens, total_output_tokens

    user_content = USER_PROMPT_TEMPLATE.format(sjt_response=sjt_response)

    for attempt in range(5):
        try:
            response = client.chat.completions.create(
                model=MODEL_ID,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPTS[prompt]},
                    {"role": "user",   "content": user_content},
                ],
                max_tokens=5,
                temperature=0.0,
            )
            raw_output = response.choices[0].message.content.strip()

            # Track token usage
            if response.usage:
                total_input_tokens  += response.usage.prompt_tokens
                total_output_tokens += response.usage.completion_tokens

            match = re.search(r'\b([1-7])\b', raw_output)
            if match:
                time.sleep(REQUEST_DELAY)
                return int(match.group(1))

            print(f"  Warning: unexpected output '{raw_output}' "
                  f"for: {sjt_response[:60]}...")
            time.sleep(REQUEST_DELAY)
            return None

        except Exception as e:
            error_str = str(e).lower()
            if "rate_limit" in error_str or "429" in error_str:
                wait = (2 ** attempt) * 5
                print(f"  Rate limit hit — waiting {wait}s "
                      f"(attempt {attempt + 1}/5)...")
                time.sleep(wait)
            else:
                print(f"  API error: {e}")
                time.sleep(REQUEST_DELAY)
                return None

    return None

# MAIN LOOP
all_results = []

for run_idx, (classification, dimension, text_col, prompt) in enumerate(RUNS, 1):

    # Build output path first so we can check if this run already completed
    safe_model_name = MODEL_ID.replace("/", "_")
    output_filename = (
        f"decoder_{classification}_{dimension}_{text_col}"
        f"_prompt{prompt}_{safe_model_name}_v{SCRIPT_VERSION}.csv"
    )
    output_path = f"{OUTPUT_DIR}/decoder_predictions/{output_filename}"

    # Skip if output already exists — allows resuming after a crash
    if os.path.exists(output_path):
        print(f"\nSkipping run {run_idx}/{len(RUNS)}: {classification} / {dimension} "
              f"/ {text_col} / prompt={prompt}")
        print(f"  Output already exists: {output_filename}")
        existing = pd.read_csv(output_path)
        all_results.append(existing)
        continue

    print(f"\n{'='*60}")
    print(f"Run {run_idx}/{len(RUNS)}: {classification} / {dimension} "
          f"/ {text_col} / prompt={prompt}")
    print(f"{'='*60}")

    data_path = f"{DATA_DIR}/{classification}_{dimension}.csv"
    df = pd.read_csv(data_path)

    if text_col not in df.columns:
        print(f"  WARNING: column '{text_col}' not found. Skipping.")
        continue

    df_clean = df[[text_col, "BIMI_mean", "ResponseId"]].dropna().reset_index(drop=True)
    print(f"  Responses to rate: {len(df_clean)}")

    ratings      = []
    failed_count = 0

    for i, row in df_clean.iterrows():
        rating = get_bimi_rating_tracked(row[text_col], prompt)

        if rating is None:
            failed_count += 1
            ratings.append(np.nan)
        else:
            ratings.append(rating)

        if (i + 1) % 50 == 0:
            est_cost = (total_input_tokens  * INPUT_COST_PER_TOKEN +
                        total_output_tokens * OUTPUT_COST_PER_TOKEN)
            print(f"  Rated {i + 1}/{len(df_clean)} | "
                  f"Est. total cost so far: ${est_cost:.2f}")

    df_clean["predicted_BIMI"] = ratings
    df_clean["actual_BIMI"]    = df_clean["BIMI_mean"]
    df_clean["classification"] = classification
    df_clean["dimension"]      = dimension
    df_clean["text_input"]     = text_col
    df_clean["prompt"]         = prompt
    df_clean["model"]          = MODEL_ID
    df_clean["model_snapshot"] = model_snapshot
    df_clean["script_version"] = SCRIPT_VERSION

    df_results = df_clean.dropna(subset=["predicted_BIMI"]).reset_index(drop=True)

    pearson_r, p_value = pearsonr(df_results["actual_BIMI"],
                                  df_results["predicted_BIMI"])
    mse  = mean_squared_error(df_results["actual_BIMI"],
                              df_results["predicted_BIMI"])
    rmse = np.sqrt(mse)

    df_results["pearson_r"] = pearson_r
    df_results["p_value"]   = p_value

    print(f"  Successful: {len(df_results)} / {len(df_clean)} | "
          f"Failed: {failed_count}")
    print(f"  Pearson r = {pearson_r:.3f}, p = {p_value:.4f}, "
          f"RMSE = {rmse:.4f}")
    print(f"  Distribution:\n"
          f"{df_results['predicted_BIMI'].value_counts().sort_index().to_string()}")

    df_results.to_csv(output_path, index=False)
    print(f"  Saved: {output_path}")

    all_results.append(df_results)

# COMBINED OUTPUT & COST SUMMARY

df_all = pd.concat(all_results, ignore_index=True)
combined_path = (
    f"{OUTPUT_DIR}/decoder_predictions/"
    f"decoder_all_runs_{MODEL_ID}_v{SCRIPT_VERSION}.csv"
)
df_all.to_csv(combined_path, index=False)

total_cost = (total_input_tokens  * INPUT_COST_PER_TOKEN +
              total_output_tokens * OUTPUT_COST_PER_TOKEN)

print(f"\n{'='*60}")
print(f"All runs complete.")
print(f"Model snapshot used: {model_snapshot}")
print(f"Total input tokens:  {total_input_tokens:,}")
print(f"Total output tokens: {total_output_tokens:,}")
print(f"Estimated total cost: ${total_cost:.2f}")
print(f"Combined file saved to:\n{combined_path}")
print(f"{'='*60}")